### ISSUE TITLE
NullPointerException when player is not authenticated

### ISSUE THREAD

**Issue by Londiuh** [Additional-Mods/simplerauth#35]
**Describe the bug**
Sometimes when a player joins, a NullPointerException shows in the console.
```log
[17:36:59] [Server thread/INFO]: player[/127.0.0.1:55354] logged in with entity id 391 at (-114.18788195628045, 76.0, -230.7402672896382)
[17:36:59] [Server thread/INFO]: player joined the game
[17:36:59] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: Cannot read field "field_1352" because "this.field_14119" is null
	at net.minecraft.class_3244.method_12050(class_3244.java:426) ~[intermediary-server.jar:?]
	at net.minecraft.class_2793.method_12085(class_2793.java:24) ~[intermediary-server.jar:?]
	at net.minecraft.class_2793.method_11054(class_2793.java:6) ~[intermediary-server.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```
This rarely happens. I saw this NullPointerException only 2 times.

`field_1352` = `Vec3d x`
`field_14119` = `requestedTeleportPos` at `ServerPlayNetworkHandler`

Maybe it's caused by [OnPlayerConnect.java#L35](https://github.com/Dqu1J/simplerauth/blob/master/src/main/java/com/dqu/simplerauth/listeners/OnPlayerConnect.java#L35)

**To Reproduce**
- Join the server

**Expected behavior**
NullPointerException doesn't happen

**Version**
Mod version: source
Minecraft version: 1.17.1
Fabric version: 0.7.4

**Comment by Dqu1J** [comment]
Can you send your currrent config file?

**Comment by Londiuh** [comment]
It's the default

**Comment by Londiuh** [comment]
Maybe in some weird cases, when `stopRiding()` is called, the player isn't fully ready.

**Comment by Dqu1J** [comment]
I dont think it is `stopRiding()`

**Comment by Londiuh** [comment]
`stopRiding()` -> `requestTeleportAndDismount()` -> `requestTeleport()`

Maybe just a coincidence, but it uses `requestedTeleportPos` (field_14119) which is null when the exception shows

**Comment by Dqu1J** [comment]
Isn't `stopRiding()`. Still occurs with `if (player.hasVehicle()) player.stopRiding();`.

**Comment by Dqu1J** [comment]
It seems to happen just randomly, it may do it multiple times too.
