### ISSUE TITLE
Can't register more then one player

### ISSUE THREAD

**Issue by Tommimon** [Additional-Mods/simplerauth#8]
**Describe the bug**
I can't register more than one player.

**To Reproduce**
Create a server with specified file versions, set online mode to false, try to login with two different players.

**Expected behavior**
Be able to add as many players as I want.

**Screenshots**
![Screenshot from 2021-06-25 23-47-47](https://user-images.githubusercontent.com/37435103/123489558-88ee3500-d612-11eb-90f3-ff4ef9d4a1d9.png)

**Version**
Mod version: 1.1.2
Minecraft version: 1.17
Fabric version: 0.7.3
Fabric API: 0.35.0

**Additional context**
I  tried to remove every other mod to avoid conflicts and I deleted the database to create a new one. The first player can register with no problems but the second can't.

**Server log**
```
[21:57:29] [Server thread/ERROR]: Command exception: /register admin admin
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at com.google.gson.JsonArray.get(JsonArray.java:183) ~[server.jar:?]
	at com.dqu.simplerauth.DbManager.getPlayer(DbManager.java:78) ~[SimplerAuth-1.1.2.jar:?]
	at com.dqu.simplerauth.DbManager.isPlayerRegistered(DbManager.java:87) ~[SimplerAuth-1.1.2.jar:?]
	at com.dqu.simplerauth.commands.RegisterCommand.lambda$registerCommand$0(RegisterCommand.java:26) ~[SimplerAuth-1.1.2.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[intermediary-server.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[intermediary-server.jar:?]
	at net.minecraft.class_2170.method_9249(class_2170.java:251) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_14370(class_3244.java:1239) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_31286(class_3244.java:1223) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_12048(class_3244.java:1206) ~[intermediary-server.jar:?]
	at net.minecraft.class_2797.method_12115(class_2797.java:30) ~[intermediary-server.jar:?]
	at net.minecraft.class_2797.method_11054(class_2797.java:7) ~[intermediary-server.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:783) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:167) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:765) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:759) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:744) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:696) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Dqu1J** [comment]
Could you please verify if that happens on the latest build?

You can download it [here](https://github.com/Dqu1J/simplerauth/actions/runs/973099176)
Under the Artifacts section, download the zip archive, named Package.
Extract the archive, and put file SimplerAuth-1.1.2.jar into your mods folder.
Then, test if the issue remains.

**Comment by Dqu1J** [comment]
1.1.3 is now released, where that bug is fixed.

**Comment by Tommimon** [comment]
I confirm that the bug is fixed for me, thanks!
